DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()



urlpatterns = [
    path("", views.home),
    path('admin/', admin.site.urls),
    path("movies/", include("movies.urls")),
    path("api/", include(movie_resource.urls))
]

movies/urls.py
from django.urls import path
from . import views

# movie/
# movies/1/details

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>",views.detail, name="detail")
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie



# Create your models here.

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

DjangoProject/views.py
from django.shortcuts import render



def home(request):
    return render(request, "home.html")

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, "movies/index.html", {"movies": movies})


def detail(request, movie_id):
        movie = get_object_or_404(Movie, pk=movie_id)
        return render(request, "movies/index.html", {"movie": movie})

movies/templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Details</title>
</head>
<body>
    {% extends 'base.html' %}


{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title}}</dd>
        <dt>Genre<dt>
        <dd>{{ movie.genre}}</dd>
        <dt>Stock</dt>
        <dd>{{ movie.number_in_stock}}</dd>
    </dl>
{% endblock %}
</body>
</html>
    

movies/templates/movies/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies List</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

    {% block content %}

    
        <h3 class="py-3 text-center">🎬 🎟🍿 Movies List 🎬 🎟🍿</h3>

            
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>🎬 Title</th>
                    <th>🚀 Genre</th>
                    <th>📌 Stock </th>
                    <th>⭐️ Daily Rate</th>
                </tr>
            </thead>
            <tbody> 
            {% for movie in movies %}
                <tr>
                    <td> <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock}}</td>
                    <td>{{ movie.daily_rate}}</td>
                </tr>
            {% endfor %}  
            </tbody>
        </table>

        {% endblock  %}
    </main>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies List</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

    <nav class="navbar bg-light py-2">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Django Project</a>
        </div>
    </nav>
<main class="container">
    {% block content %}
        
    {% endblock %}
</main>    
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    {% extends 'base.html' %}


    
    {% block content %}
        <a href="{% url 'movies:index' %}">Movies</a>
    {% endblock %}
        
</body>
</html>